# Generated by Django 6.0.5 on 2026-06-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="available_rooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="total_rooms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
